.MODEL SMALL
.STACK 100H
.DATA
STRING1 DB 'WELCOME USER!! $'
STRING2 DB 0AH,0DH,'PLEASE USER ENTER LETTER 1: $'
STRING3 DB 0AH,0DH,'PLEASE USER ENTER LETTER 2: $'
STRING4 DB 0AH,0DH,'PLEASE USER ENTER LETTER 3: $'
OUTPUT DB 0AH,0DH,'OUTPUT: $' 
LETTER DB ?
.CODE

MAIN PROC
    MOV AX,@DATA
    MOV DS,AX
    
    LEA DX,STRING1
    MOV AH,9
    INT 21H
    
    LEA DX,STRING2
    MOV AH,9
    INT 21H
    
    MOV AH,1
    INT 21H
    MOV BL,AL
    
    LEA DX,STRING3
    MOV AH,9
    INT 21H
    MOV AH,1
    INT 21H
    MOV CL,AL
    
    LEA DX,STRING4
    MOV AH,9
    INT 21H
    MOV AH,1
    INT 21H
    MOV LETTER,AL
      

TASK PROC
    LEA DX,OUTPUT
    MOV AH,9
    INT 21H
    
    ;MOV DX,0H
    
    MOV AH,2
    MOV DX,0AH
    INT 21H
    MOV AH,2
    MOV DX,0DH
    INT 21H
    MOV AH,2
    MOV DL,BL
    INT 21H 
    
    MOV AH,2
    MOV DX,0AH
    INT 21H
    MOV AH,2
    MOV DX,0DH
    INT 21H
    MOV AH,2
    MOV DL,CL
    INT 21H
    
    MOV AH,2
    MOV DX,0AH
    INT 21H
    MOV AH,2
    MOV DX,0DH
    INT 21H
    MOV AH,2
    MOV DL,LETTER
    INT 21H
    RET

EXIT:
MOV AH,4CH
INT 21H
TASK ENDP
END  MAIN