.MODEL SMALL
.STACK 100H
.DATA
STRING1 DB 'WELCOME TO MY CALCULATOR!! $'
STRING2 DB 0AH,0DH,'PLEASE USER ENTER A HEX DIGIT (A-F): $'
STRING3 DB 0AH,0DH,'IN DECIMAL IT IS: $'
STRING4 DB 0AH,0DH,'THANK YOU FOR USING MY CALCULATOR$'
STRING5 DB 0AH,0DH,'HAVE A GOOD DAY $' 
LETTER DB ?
.CODE

MAIN PROC
    MOV AX,@DATA
    MOV DS,AX
    
    LEA DX,STRING1
    MOV AH,9
    INT 21H
    
    LEA DX,STRING2
    MOV AH,9
    INT 21H
    
    MOV AH,1
    INT 21H
    MOV BL,AL
    
    CALL TASK
    JMP EXIT
      

TASK PROC
    LEA DX,STRING3
    MOV AH,9
    INT 21H
    MOV AH,2
    MOV DL,31H
    INT 21H
    SUB BL,11H
    MOV AH,2
    MOV DL,BL
    INT 21H
    
    LEA DX,STRING4
    MOV AH,9
    INT 21H
    LEA DX,STRING5
    MOV AH,9
    INT 21H
    
    RET

EXIT:
MOV AH,4CH
INT 21H
TASK ENDP
END  MAIN